### ISSUE TITLE
permissions problems with fastqc

### ISSUE THREAD

**Issue by charlesreid1** [dahak-metagenomics/dahak#72]
Using the biocontainer image for fastqc is leading to some trouble with file permissions, even when run in singularity. The permissions issue appears to be occurring _within_ the container, i.e., one step writes files owned by root and the next step can't read them.

I also had this permissions issue using the fastqc Dockerfile in this repository, and also using a Dockerfile based on miniconda.

Am wondering if you've seen this issue before @brooksph?

If I get a bash shell in the container while fastqc is executing, the file permissions all look fine except for one file, an HTML file, that is owned by root, It's called `SRR606249_2_reads_fastqc.html`. So fastqc generates the report as root??

Output:

```
Started analysis of SRR606249_2_reads.fq.gz
Approx 5% complete for SRR606249_2_reads.fq.gz
Approx 10% complete for SRR606249_2_reads.fq.gz
Approx 15% complete for SRR606249_2_reads.fq.gz
...
Approx 90% complete for SRR606249_2_reads.fq.gz
Approx 95% complete for SRR606249_2_reads.fq.gz
Analysis complete for SRR606249_2_reads.fq.gz
Error in rule pre_trimming_quality_assessment:
    jobid: 0
    output: data/SRR606249_2_reads_fastqc.zip

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/executors.py", line 379, in _callback
    callback(job)
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/scheduler.py", line 330, in _proceed
    self.get_executor(job).handle_job_success(job)
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/executors.py", line 392, in handle_job_success
    super().handle_job_success(job)
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/executors.py", line 199, in handle_job_success
    ignore_missing_output=ignore_missing_output)
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/dag.py", line 373, in check_and_touch_output
    f.touch()
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/io.py", line 319, in touch
    raise e
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/io.py", line 310, in touch
    lutime(self.file, times)
  File "/home/ubuntu/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/snakemake/io.py", line 37, in lutime
    os.utime(f, times, follow_symlinks=False)
PermissionError: [Errno 13] Permission denied
Removing output files of failed job pre_trimming_quality_assessment since they might be corrupted:
data/SRR606249_2_reads_fastqc.zip
```

I'm confused why this is happening now. Is it possible the data files have root-owned files zipped up in them? (Can't imagine how that would possibly cause this though.)

**Comment by charlesreid1** [comment]
my docker run cmd:

```
+ docker run -v /home/ubuntu/dahak-taco/data/:/data/ -it quay.io/biocontainers/fastqc:0.11.7--pl5.22.0_2 fastqc -t 1 /data/SRR606249_2_reads.fq.gz -o /data/
```

(`-t` specifies # of threads). And in read filtering walkthrough:

```
docker run -v ${PWD}:/data -it biocontainers/fastqc fastqc /data/SRR606249_subset10_1.fq.gz -o /data/qc/before_trim
```

**Comment by charlesreid1** [comment]
Okay, looks like at some point I had added, and then inadvertently removed, the `-u` flag to run the docker container as a user with a specified uid/gid. Fixed by adding the following to the docker run command:

```
docker run -u "$(id -u):$(id -g)" ...
```
